name: urbantutorsapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.8.0
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  dio: ^5.8.0+1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/urban.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/urban.png"
